### ISSUE TITLE
Adding multiple sliders on one page

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-svg-slideshow-changelog#1]
The second Slider breaks. Check my example:
https://manuelvonrotz.ch/sliderbug/

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We have updated the component to fix this issue. You can get the updated js code here:
https://codyhouse.co/ds/components/app/svg-slideshow

Feel free to reopen this issue if you are still having this problem. Cheers.

**Comment by matobeag** [comment]
wonderful 🙌 thank you
